name: Generate Stargazers Badge

on:
  schedule:
    - cron: '0 * * * *' # run hourly
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write

jobs:
  fetch-stargazers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch stargazers total
        run: |
          REPOS=(
            "agjjQuery/agjjQuery"
            "andrewgjohnson/agjCalendar"
          )
          TOTAL_STARGAZERS=0
          UNIQUE_IDS=()

          for REPO in "${REPOS[@]}"; do
            PAGE=1
            while true; do
              RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO/stargazers?per_page=100&page=$PAGE")
              if echo $RESPONSE | jq -e 'type == "array"' > /dev/null; then
                IDS=$(echo $RESPONSE | jq '.[].id')
                if [ -z "$IDS" ]; then
                  break
                fi
                for ID in $IDS; do
                  if [[ ! " ${UNIQUE_IDS[@]} " =~ " ${ID} " ]]; then
                    UNIQUE_IDS+=("$ID")
                  fi
                done
                if [ $(echo $RESPONSE | jq '. | length') -lt 5 ]; then
                  break
                fi
                PAGE=$((PAGE + 1))
              else
                echo "Error or no stargazers found for $REPO"
                break
              fi
            done
          done
          TOTAL_STARGAZERS=${#UNIQUE_IDS[@]}
          echo "Total Stargazers: $TOTAL_STARGAZERS"
          echo "TOTAL_STARGAZERS=$TOTAL_STARGAZERS" >> $GITHUB_ENV

      - name: Update badge
        run: |
          BADGE_URL="https://raster.shields.io/badge/stargazers-"

          if [ $TOTAL_STARGAZERS -ge 999500 ]; then
            ROUNDED_STARGAZERS=$(( (TOTAL_STARGAZERS) / 1000000 ))
            BADGE_URL="${BADGE_URL}${ROUNDED_STARGAZERS}M"
          elif [ $TOTAL_STARGAZERS -ge 1000 ]; then
            ROUNDED_STARGAZERS=$(( (TOTAL_STARGAZERS) / 1000 ))
            BADGE_URL="${BADGE_URL}${ROUNDED_STARGAZERS}k"
          else
            BADGE_URL="${BADGE_URL}${TOTAL_STARGAZERS}"
          fi

          BADGE_URL="${BADGE_URL}-0366d6.png?colorB=0366d6&style=flat-square&logoColor=white&logo=github"

          echo "Downloading badge from URL: $BADGE_URL"
          curl -L "$BADGE_URL" -o documentation/agjjQuery.org/images/stargazers-badge.png

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add documentation/agjjQuery.org/images/stargazers-badge.png
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update badge"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
