name: Generate Contributors Badge

on:
  schedule:
    - cron: '0 * * * *' # run hourly
  workflow_dispatch: # allow manual triggering

permissions:
  contents: write

jobs:
  fetch-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch contributors total
        run: |
          REPOS=(
            "agjjQuery/agjjQuery"
            "andrewgjohnson/agjCalendar"
          )
          TOTAL_CONTRIBUTORS=0
          UNIQUE_IDS=()

          for REPO in "${REPOS[@]}"; do
            PAGE=1
            while true; do
              RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$REPO/contributors?per_page=100&page=$PAGE")
              if echo $RESPONSE | jq -e 'type == "array"' > /dev/null; then
                IDS=$(echo $RESPONSE | jq '.[].id')
                if [ -z "$IDS" ]; then
                  break
                fi
                for ID in $IDS; do
                  if [[ ! " ${UNIQUE_IDS[@]} " =~ " ${ID} " ]]; then
                    UNIQUE_IDS+=("$ID")
                  fi
                done
                if [ $(echo $RESPONSE | jq '. | length') -lt 100 ]; then
                  break
                fi
                PAGE=$((PAGE + 1))
              else
                echo "Error or no contributors found for $REPO"
                break
              fi
            done
          done
          TOTAL_CONTRIBUTORS=${#UNIQUE_IDS[@]}
          echo "Total Contributors: $TOTAL_CONTRIBUTORS"
          echo "TOTAL_CONTRIBUTORS=$TOTAL_CONTRIBUTORS" >> $GITHUB_ENV

      - name: Update badge
        run: |
          BADGE_URL="https://raster.shields.io/badge/contributors-"

          if [ $TOTAL_CONTRIBUTORS -ge 999500 ]; then
            ROUNDED_CONTRIBUTORS=$(( (TOTAL_CONTRIBUTORS) / 1000000 ))
            BADGE_URL="${BADGE_URL}${ROUNDED_CONTRIBUTORS}M"
          elif [ $TOTAL_CONTRIBUTORS -ge 1000 ]; then
            ROUNDED_CONTRIBUTORS=$(( (TOTAL_CONTRIBUTORS) / 1000 ))
            BADGE_URL="${BADGE_URL}${ROUNDED_CONTRIBUTORS}k"
          else
            BADGE_URL="${BADGE_URL}${TOTAL_CONTRIBUTORS}"
          fi

          BADGE_URL="${BADGE_URL}-0366d6.png?colorB=0366d6&style=flat-square&logoColor=white&logo=github"

          echo "Downloading badge from URL: $BADGE_URL"
          curl -L "$BADGE_URL" -o documentation/agjjQuery.org/images/contributors-badge.png

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add documentation/agjjQuery.org/images/contributors-badge.png
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update badge"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
